### ISSUE TITLE
Internal webserver has failed to start

### ISSUE THREAD

**Issue by TLengert** [BillyGalbreath/VS-LiveMap#3] opened 2024-07-11 21:21 UTC
Just installed the latest version on git and troubleshooting the below error.

11.7.2024 15:14:11 [Server Error] [LiveMap] Internal webserver has failed to start
11.7.2024 15:14:11 [Server Error] [LiveMap] System.Net.HttpListenerException (5): Access is denied.

**Comment by BillyGalbreath** [comment] 2024-07-11 22:55
Duplicate of #2

**Closed as completed by BillyGalbreath** 2024-07-11 22:55 UTC
Labels: works as intended
